[package]
name = "resolver"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.1"
scarb-version = "2.9.1"
authors = ["LFG Labs"]
description = "Resolver CCIP"
documentation = "https://github.com/lfglabs-dev/resolver_ccip"
readme = "README.md"
repository = "https://github.com/lfglabs-dev/resolver_ccip"

[dependencies]
starknet = "2.9.1"
openzeppelin_access = "0.20.0"
openzeppelin_token = "0.20.0"
#naming = { git = "https://github.com/starknet-id/naming.git", rev = "7fa861a7a6e56c96ba3b508c66d7587d2597385a" }
#identity = { git = "https://github.com/starknet-id/identity.git", rev = "5ae7fafdd20abf4b1e789b83af5db7e23ad39a7c" }

[dev-dependencies]
cairo_test = "2.9.1"
openzeppelin_utils = "0.20.0"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true

# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = true
